name: Build APK from ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Extract Project
        run: |
          unzip -o Offline_games_duel_Android_Project.zip -d project
          echo "ISI PROJECT:"
          find project -maxdepth 3 -type f | head -50

      - name: Find Android Project
        run: |
          PROJECT_DIR=$(dirname "$(find project -name settings.gradle -type f | head -n 1)")
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Project ditemukan: $PROJECT_DIR"

      - name: Download Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.9-bin.zip
          unzip -q gradle-8.9-bin.zip
          echo "$PWD/gradle-8.9/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          gradle assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: project/**/app/build/outputs/apk/debug/*.apk
